### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yiyouguisu** [lenve/VBlog#2]
![image](https://user-images.githubusercontent.com/11996269/34637443-14d47f00-f2f2-11e7-9133-e817f10b3e20.png)

**Comment by yiyouguisu** [comment]
@lenve

**Comment by lenve** [comment]
有没有其他信息呢？
你是用IDEA吗？直接导入就报错吗？
看错误提示是userMapper找不到，首先检查下这个类是否存在，然后确认下这个类上的注解```@Mapper```是否存在。
@yiyouguisu

**Comment by yiyouguisu** [comment]
@lenve 导入是报数据源错误，我已经处理了，但是报Mapper找不到，用的是IDEA,@Mapper是有的
![image](https://user-images.githubusercontent.com/11996269/34699221-0c7c76ba-f517-11e7-8372-03b12904e924.png)


![image](https://user-images.githubusercontent.com/11996269/34699208-ffc5dc36-f516-11e7-8b27-a4d12003429b.png)
