### ISSUE TITLE
“Cannot determine embedded database driver class for database type NONE”问题的解决办法

### ISSUE THREAD

**Issue by liyufomm** [lenve/VBlog#6]
遇到奇怪的问题，得把 pom.xml <build>里的resource删掉，才能正常启动，否则报错“Cannot determine embedded database driver class for database type NONE”：
>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.xml</include>
				</includes>
			</resource>
		</resources>

但删掉该resource后，就需要把mapper包中的xml移动到main/resources/mapper目录下，同时在application.properties中添加
mybatis.mapper-locations=classpath:/mapper/*.xml

**Comment by lenve** [comment]
请参考https://github.com/lenve/vhr/issues/2
